name = "Mages and Mechanics"
author = "7actose"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a52604041c91afe84584aeafceda8791f87669b232a0721996c30516cfd69953"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
