name = "Mages and Mechanics"
author = "7actose"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdfa6494fb326b9bd0701af0982951db9bd981bc2b7514bdddcc36194fa1232f"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
