name = "Mages and Mechanics"
author = "7actose"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c69a1d475ae20ded96050fdf190be528bbdbb7288aa7aab1f94914a210fc9397"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
