name = "Mages and Mechanics"
author = "7actose"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f05afad59659504f50ad74153ae9e6565a5528f4828d729b3908133ff0ec2d4"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
