name = "Mages and Mechanics"
author = "7actose"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd8faf0a3ca3cc90001ecf819aa6ef23394414d719e30ad7c47c6c44b798ab3c"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
